/**
 * In-app licenses text — keep in sync with LICENSES.md at the repo root.
 */

export type LicenseLink = {
  label: string;
  url: string;
};

export type LicenseBullet = {
  label: string;
  body: string;
  link?: LicenseLink;
};

export type LicenseSection = {
  title: string;
  paragraphs: string[];
  bullets?: LicenseBullet[];
};

export const LICENSES_SCREEN_TITLE = 'Licenses and Attribution';

export const LICENSE_SECTIONS: LicenseSection[] = [
  {
    title: 'Chess piece graphics — cburnett set',
    paragraphs: [
      'This app uses the cburnett chess piece set for on-screen piece rendering.',
      'The SVG path data is embedded locally in components/cburnettPieceSvgs.ts for offline use. When sharing or modifying adapted versions of these graphics, retain attribution and comply with the CC BY-SA 3.0 license terms (including ShareAlike where applicable).',
    ],
    bullets: [
      {
        label: 'Author',
        body: 'Colin M.L. Burnett',
      },
      {
        label: 'License',
        body: 'Creative Commons Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)',
        link: {
          label: 'creativecommons.org/licenses/by-sa/3.0/',
          url: 'https://creativecommons.org/licenses/by-sa/3.0/',
        },
      },
      {
        label: 'Source',
        body: 'Lichess lila repository — public/piece/cburnett/',
        link: {
          label: 'github.com/lichess-org/lila/tree/master/public/piece/cburnett',
          url: 'https://github.com/lichess-org/lila/tree/master/public/piece/cburnett',
        },
      },
    ],
  },
  {
    title: 'Stockfish chess engine',
    paragraphs: [
      'This app uses Stockfish 18 (GPL-3.0) as an on-device analysis engine.',
      'Stockfish is Copyright the Stockfish developers (see vendor/Stockfish/Copying.txt). The engine is not linked into the app\'s native binary.',
      'Integration: The engine runs in an isolated hidden WebView and communicates with the app via UCI text over postMessage only.',
    ],
    bullets: [
      {
        label: 'License',
        body: 'GNU General Public License v3.0 (GPL-3.0)',
        link: {
          label: 'gnu.org/licenses/gpl-3.0.en.html',
          url: 'https://www.gnu.org/licenses/gpl-3.0.en.html',
        },
      },
      {
        label: 'Project',
        body: 'Stockfish chess engine',
        link: {
          label: 'stockfishchess.org',
          url: 'https://stockfishchess.org',
        },
      },
      {
        label: 'Source code',
        body: 'official-stockfish/Stockfish (submodule at vendor/Stockfish, tag sf_18)',
        link: {
          label: 'github.com/official-stockfish/Stockfish',
          url: 'https://github.com/official-stockfish/Stockfish',
        },
      },
      {
        label: 'Runtime build',
        body: 'WebAssembly port from nmrugg/stockfish.js release v18.0.0 (stockfish-18-lite-single), bundled offline in assets/stockfish/',
        link: {
          label: 'github.com/nmrugg/stockfish.js',
          url: 'https://github.com/nmrugg/stockfish.js',
        },
      },
    ],
  },
  {
    title: 'Opening book (ECO)',
    paragraphs: [
      'Move classification uses a bundled opening database derived from the public lichess-org/chess-openings dataset (CC0 / public domain).',
      'Bundled file: assets/openings/eco-book.json (generated by npm run openings:sync).',
      'Lookup: Prefix trie keyed by SAN move sequence for offline book detection.',
    ],
    bullets: [
      {
        label: 'Source',
        body: 'lichess-org/chess-openings',
        link: {
          label: 'github.com/lichess-org/chess-openings',
          url: 'https://github.com/lichess-org/chess-openings',
        },
      },
    ],
  },
];

/** Plain-text export matching LICENSES.md for verification. */
export const LICENSES_PLAIN_TEXT = `# ${LICENSES_SCREEN_TITLE}

## Chess piece graphics — cburnett set

This app uses the **cburnett** chess piece set for on-screen piece rendering.

- **Author:** Colin M.L. Burnett
- **License:** Creative Commons Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) — https://creativecommons.org/licenses/by-sa/3.0/
- **Source:** Lichess lila repository — \`public/piece/cburnett/\` — https://github.com/lichess-org/lila/tree/master/public/piece/cburnett

The SVG path data is embedded locally in \`components/cburnettPieceSvgs.ts\` for offline use. When sharing or modifying adapted versions of these graphics, retain attribution and comply with the CC BY-SA 3.0 license terms (including ShareAlike where applicable).

## Stockfish chess engine

This app uses **Stockfish 18** (GPL-3.0) as an on-device analysis engine.

- **Official source:** github.com/official-stockfish/Stockfish (submodule at \`vendor/Stockfish\`, tag \`sf_18\`)
- **Runtime build:** WebAssembly port from nmrugg/stockfish.js release v18.0.0 (\`stockfish-18-lite-single\`), bundled offline in \`assets/stockfish/\`
- **Integration:** The engine runs in an isolated hidden WebView and communicates with the app via UCI text over \`postMessage\` only

Stockfish is Copyright the Stockfish developers (see \`vendor/Stockfish/Copying.txt\`). The engine is not linked into the app's native binary.

- **License:** GNU General Public License v3.0 — https://www.gnu.org/licenses/gpl-3.0.en.html
- **Project:** https://stockfishchess.org

## Opening book (ECO)

Move classification uses a bundled opening database derived from the public **lichess-org/chess-openings** dataset (CC0 / public domain).

- **Bundled file:** \`assets/openings/eco-book.json\` (generated by \`npm run openings:sync\`)
- **Lookup:** Prefix trie keyed by SAN move sequence for offline book detection
- **Source:** https://github.com/lichess-org/chess-openings
`;
